PANDAS-PANNEL DATA ANALYSIS

In [2]:
#pandas:pannal data analysis(stores data in tabular format)
import pandas as pd
import numpy as np
pd.__version__

'2.2.2'

In [11]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Creating a series

#creating a series
s=pd.Series(a)
s

In [15]:
s=pd.Series(a,index=[11,12,13,14,15,16,17,18,19])
s

11    1
12    2
13    3
14    4
15    5
16    6
17    7
18    8
19    9
dtype: int32

DATA FRAME IN ONE FRAME

In [2]:
#np.nan:used to represent null values
stu={'Name':['A','B','C','D','E','F','G','H','I','J'],
     'Roll_no':[11,12,13,14,15,16,17,18,19,20],
     'Course':['AI AND ML','DA','PYTHON','WEB-DESIGN','GENAI','DSA','IOT','CLOUD','CYBER_SECURITY','JAVA']}
stu

{'Name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
 'Roll_no': [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 'Course': ['AI AND ML',
  'DA',
  'PYTHON',
  'WEB-DESIGN',
  'GENAI',
  'DSA',
  'IOT',
  'CLOUD',
  'CYBER_SECURITY',
  'JAVA']}

In [3]:
df=pd.DataFrame(stu)
print(df)
df

  Name  Roll_no          Course
0    A       11       AI AND ML
1    B       12              DA
2    C       13          PYTHON
3    D       14      WEB-DESIGN
4    E       15           GENAI
5    F       16             DSA
6    G       17             IOT
7    H       18           CLOUD
8    I       19  CYBER_SECURITY
9    J       20            JAVA

  Name  Roll_no          Course
0    A       11       AI AND ML
1    B       12              DA
2    C       13          PYTHON
3    D       14      WEB-DESIGN
4    E       15           GENAI
5    F       16             DSA
6    G       17             IOT
7    H       18           CLOUD
8    I       19  CYBER_SECURITY
9    J       20            JAVA

In [30]:
#head():display the top 5 rows of a dataframe
df.head()

  Name  Roll_no      Course
0    A       11   AI AND ML
1    B       12          DA
2    C       13      PYTHON
3    D       14  WEB-DESIGN
4    E       15       GENAI

In [33]:
df.head(1)

  Name  Roll_no     Course
0    A       11  AI AND ML

In [34]:
#tail():display the bottom 5 rows of a dataset
df.tail()

  Name  Roll_no          Course
5    F       16             DSA
6    G       17             IOT
7    H       18           CLOUD
8    I       19  CYBER_SECURITY
9    J       20            JAVA

In [35]:
df.tail(1)

  Name  Roll_no Course
9    J       20   JAVA

In [36]:
#info():display the complete details of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     10 non-null     object
 1   Roll_no  10 non-null     int64
 2   Course   10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [37]:
#dtype:use to see the datatype of every column
df.dtypes

Name       object
Roll_no     int64
Course     object
dtype: object

In [39]:
#isnull():use to see the null values present in the datasets
df.isnull()

    Name  Roll_no  Course
0  False    False   False
1  False    False   False
2  False    False   False
3  False    False   False
4  False    False   False
5  False    False   False
6  False    False   False
7  False    False   False
8  False    False   False
9  False    False   False

In [40]:
df.isnull().sum()

Name       0
Roll_no    0
Course     0
dtype: int64

In [45]:
#np.nan:used to represent null values
spd={'Name':['A','B','C','D','E','F','G','H','I','J'],
     'Roll_no':[11,12,13,14,15,16,17,18,19,np.nan],
     'Course':['AI AND ML','DA','PYTHON','WEB-DESIGN','GENAI','DSA','IOT','CLOUD','CYBER_SECURITY','JAVA']}
spd

{'Name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
 'Roll_no': [11, 12, 13, 14, 15, 16, 17, 18, 19, nan],
 'Course': ['AI AND ML',
  'DA',
  'PYTHON',
  'WEB-DESIGN',
  'GENAI',
  'DSA',
  'IOT',
  'CLOUD',
  'CYBER_SECURITY',
  'JAVA']}

In [71]:
dfe=pd.DataFrame(spd)
dfe

  Name  Roll_no          Course
0    A     11.0       AI AND ML
1    B     12.0              DA
2    C     13.0          PYTHON
3    D     14.0      WEB-DESIGN
4    E     15.0           GENAI
5    F     16.0             DSA
6    G     17.0             IOT
7    H     18.0           CLOUD
8    I     19.0  CYBER_SECURITY
9    J      NaN            JAVA

In [48]:
dfe.isnull().sum()

Name       0
Roll_no    1
Course     0
dtype: int64

In [16]:
#used to ignore warnigs (ex that occured in fillna())
import warnings
warnings.filterwarnings('ignore')

In [66]:
#fillna():used to fill null values
dfe.Roll_no.fillna(20,inplace=True)

In [68]:
dfe.isnull().sum()

Name       0
Roll_no    0
Course     0
dtype: int64

In [67]:
dfe

  Name  Roll_no          Course
0    A     11.0       AI AND ML
1    B     12.0              DA
2    C     13.0          PYTHON
3    D     14.0      WEB-DESIGN
4    E     15.0           GENAI
5    F     16.0             DSA
6    G     17.0             IOT
7    H     18.0           CLOUD
8    I     19.0  CYBER_SECURITY
9    J     20.0            JAVA

In [75]:
dfe['Roll_no']=df['Roll_no'].fillna(20)

In [76]:
dfe

  Name  Roll_no          Course
0    A       11       AI AND ML
1    B       12              DA
2    C       13          PYTHON
3    D       14      WEB-DESIGN
4    E       15           GENAI
5    F       16             DSA
6    G       17             IOT
7    H       18           CLOUD
8    I       19  CYBER_SECURITY
9    J       20            JAVA

In [77]:
dfe.isnull().sum()

Name       0
Roll_no    0
Course     0
dtype: int64

In [81]:
#describe(use to see the statistical information of the data)
df.describe(include="all")

       Name   Roll_no     Course
count    10  10.00000         10
unique   10       NaN         10
top       A       NaN  AI AND ML
freq      1       NaN          1
mean    NaN  15.50000        NaN
std     NaN   3.02765        NaN
min     NaN  11.00000        NaN
25%     NaN  13.25000        NaN
50%     NaN  15.50000        NaN
75%     NaN  17.75000        NaN
max     NaN  20.00000        NaN

In [82]:
#unique():use to see the unique value of every column
df.Name.unique()

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype=object)

In [86]:
for i in df.columns:
    print(i,':',df[i].unique())

Name : ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']
Roll_no : [11 12 13 14 15 16 17 18 19 20]
Course : ['AI AND ML' 'DA' 'PYTHON' 'WEB-DESIGN' 'GENAI' 'DSA' 'IOT' 'CLOUD'
 'CYBER_SECURITY' 'JAVA']

In [93]:
#renaame():use to rename the column name
df=df.rename(columns={'Name':'Stu_Name'})
df

  Stu_Name  Roll_no          Course
0        A       11       AI AND ML
1        B       12              DA
2        C       13          PYTHON
3        D       14      WEB-DESIGN
4        E       15           GENAI
5        F       16             DSA
6        G       17             IOT
7        H       18           CLOUD
8        I       19  CYBER_SECURITY
9        J       20            JAVA

working with real world data
--uci machine learning repository
--kaggle

In [95]:
#to load the dataset
#syntax
#---->pd.read_file_extention(r'path of the file')
iris=pd.read_csv("C:\Users\ASUS\Downloads\iris\iris.data")
iris

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (1277638944.py, line 4)

In [96]:
#to load the dataset
#syntax
#---->pd.read_file_extention(r'path of the file')
iris=pd.read_csv(r"C:\Users\ASUS\Downloads\iris\iris.data")
iris

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [97]:
#where data has gone to header
iris=pd.read_csv(r"C:\Users\ASUS\Downloads\iris\iris.data",header=None)
iris

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [103]:
#rename the column name
iris.columns=['Sepal length','Sepal width','Petal length','Petal width','Class']
iris

     Sepal length  Sepal width  Petal length  Petal width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [104]:
iris.tail()

     Sepal length  Sepal width  Petal length  Petal width           Class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [105]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal length  150 non-null    float64
 1   Sepal width   150 non-null    float64
 2   Petal length  150 non-null    float64
 3   Petal width   150 non-null    float64
 4   Class         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [106]:
iris.dtypes

Sepal length    float64
Sepal width     float64
Petal length    float64
Petal width     float64
Class            object
dtype: object

In [107]:
iris.isnull().sum()

Sepal length    0
Sepal width     0
Petal length    0
Petal width     0
Class           0
dtype: int64

In [108]:
iris.describe(include='all')

        Sepal length  Sepal width  Petal length  Petal width        Class
count     150.000000   150.000000    150.000000   150.000000          150
unique           NaN          NaN           NaN          NaN            3
top              NaN          NaN           NaN          NaN  Iris-setosa
freq             NaN          NaN           NaN          NaN           50
mean        5.843333     3.054000      3.758667     1.198667          NaN
std         0.828066     0.433594      1.764420     0.763161          NaN
min         4.300000     2.000000      1.000000     0.100000          NaN
25%         5.100000     2.800000      1.600000     0.300000          NaN
50%         5.800000     3.000000      4.350000     1.300000          NaN
75%         6.400000     3.300000      5.100000     1.800000          NaN
max         7.900000     4.400000      6.900000     2.500000          NaN

In [110]:
for i in iris.columns:
    print(i,':',iris[i].unique())

Sepal length : [5.1 4.9 4.7 4.6 5.  5.4 4.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3 7.  6.4 6.9
 6.5 6.3 6.6 5.9 6.  6.1 5.6 6.7 6.2 6.8 7.1 7.6 7.3 7.2 7.7 7.4 7.9]
Sepal width : [3.5 3.  3.2 3.1 3.6 3.9 3.4 2.9 3.7 4.  4.4 3.8 3.3 4.1 4.2 2.3 2.8 2.4
 2.7 2.  2.2 2.5 2.6]
Petal length : [1.4 1.3 1.5 1.7 1.6 1.1 1.2 1.  1.9 4.7 4.5 4.9 4.  4.6 3.3 3.9 3.5 4.2
 3.6 4.4 4.1 4.8 4.3 5.  3.8 3.7 5.1 3.  6.  5.9 5.6 5.8 6.6 6.3 6.1 5.3
 5.5 6.7 6.9 5.7 6.4 5.4 5.2]
Petal width : [0.2 0.4 0.3 0.1 0.5 0.6 1.4 1.5 1.3 1.6 1.  1.1 1.8 1.2 1.7 2.5 1.9 2.1
 2.2 2.  2.4 2.3]
Class : ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

In [2]:
auto=pd.read_csv(r"C:\Users\ASUS\Desktop\auto-mpg.csv")
auto

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [4]:
auto.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [5]:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [6]:
auto.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [7]:
auto.horsepower.unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [8]:
for i in auto.columns:
    print(i,':',sum(auto[i]=='?'))

mpg : 0
cylinders : 0
displacement : 0
horsepower : 6
weight : 0
acceleration : 0
model year : 0
origin : 0
car name : 0

## when we have missing values in object column we can replace taht value with the top repeated value.

## when we have missing values in object column we can replace taht value with mean(average) value

In [13]:
d=auto.describe(include='all')
d

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,398.000000,398.000000,398.000000,398,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,NaN,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,NaN,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,NaN,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,NaN,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,NaN,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.000000,NaN

In [17]:
#replace():use to replace a value with another value
auto.horsepower=auto.horsepower.replace('?',d['horsepower'][2])

In [18]:
for i in auto.columns:
    print(i,':',sum(auto[i]=='?'))

mpg : 0
cylinders : 0
displacement : 0
horsepower : 0
weight : 0
acceleration : 0
model year : 0
origin : 0
car name : 0

In [22]:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [23]:
#astype():use to changee datatype of a column
auto.horsepower=auto.horsepower.astype('int64')

In [24]:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower        int64
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [46]:
titan=pd.open_csv(r"C:\Users\ASUS\Downloads\titanic dataset.csv")
titan

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
titan.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
titan.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [10]:
titan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [11]:
titan.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [49]:
titan=titan.drop('Cabin',axis=1)
titan

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Q

In [50]:
titan.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.002015,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,29.699118,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [51]:
titan.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [52]:
titan.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
count,891.000000,891.000000,891.000000,891,891,891.000000,891.000000,891.000000,891,891.000000,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,13.002015,1.102743,0.806057,NaN,49.693429,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,22.000000,0.000000,0.000000,NaN,7.910400,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,29.699118,0.000000,0.000000,NaN,14.454200,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,35.000000,1.000000,0.000000,NaN,31.000000,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN

In [47]:
#fillna(): use to fill thhe missing value
t=titan.Age.fillna(titan.Age.mean(),inplace=True)
t
#titan['Age']=titan['Age'].fillna(titan.Age.mean())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_9440\465314235.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  t=titan.Age.fillna(titan.Age.mean(),inplace=True)

In [53]:
titan.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [56]:
#dropna():use to delete the entire row that having the null values
titan=titan.dropna()
titan

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Q

In [57]:
titan.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [91]:
movi=pd.read_excel(r"C:\Users\ASUS\Desktop\movie_dataset_.xlsx")
movi

,Movie_Name,Genre,Rating,Box_Office_Crore,Franchise_Name,Location,Popularity
0,Dune,Action,1.0,175.0,Avatar Universe,bangalore,87%
1,Matrix,Action,NaN,169.0,DC,mUMbAI,71%
2,Joker,Drama,4.0,222.0,Star Wars,Chennai,88%
3,Joker,Action,8.0,NaN,DC,Bangalore,86%
4,Titanic,Action,1.0,445.0,Marvel,mumbai,74%
...,...,...,...,...,...,...,...
195,Batman,Action,1.0,264.0,Mission Impossible,DELHI,63%
196,Interstellar,Action,NaN,356.0,Fast & Furious,mumbai,75%
197,Frozen,Drama,9.0,492.0,?,CHENNAI,96%
198,Up,Comedy,10.0,394.0,Fast & Furious,MUMBAI,76%
199,Joker,Comedy,1.0,352.0,Harry Potter,koLkATa,69%

In [92]:
movi.dtypes

Movie_Name           object
Genre                object
Rating              float64
Box_Office_Crore    float64
Franchise_Name       object
Location             object
Popularity           object
dtype: object

In [93]:
movi.describe(include='all')

,Movie_Name,Genre,Rating,Box_Office_Crore,Franchise_Name,Location,Popularity
count,200,200,170.000000,185.000000,200,200,200
unique,15,5,NaN,NaN,8,65,50
top,Joker,Sci-Fi,NaN,NaN,?,MUMBAI,83%
freq,24,45,NaN,NaN,41,13,8
mean,NaN,NaN,5.323529,279.513514,NaN,NaN,NaN
std,NaN,NaN,2.731805,123.164176,NaN,NaN,NaN
min,NaN,NaN,1.000000,50.000000,NaN,NaN,NaN
25%,NaN,NaN,3.000000,177.000000,NaN,NaN,NaN
50%,NaN,NaN,5.000000,272.000000,NaN,NaN,NaN
75%,NaN,NaN,8.000000,388.000000,NaN,NaN,NaN
max,NaN,NaN,10.000000,500.000000,NaN,NaN,NaN

In [94]:
movi.isnull().sum()

Movie_Name           0
Genre                0
Rating              30
Box_Office_Crore    15
Franchise_Name       0
Location             0
Popularity           0
dtype: int64

In [95]:
for i in movi.columns:
    print(i,':',movi[i].unique())

Movie_Name : ['Dune' 'Matrix' 'Joker' 'Titanic' 'Tenet' 'Gladiator' 'Up' 'Inception'
 'Batman' 'Iron Man' 'Superman' 'Frozen' 'Coco' 'Interstellar' 'Avatar']
Genre : ['Action' 'Drama' 'Sci-Fi' 'Comedy' 'Thriller']
Rating : [ 1. nan  4.  8.  6.  3.  7. 10.  5.  9.  2.]
Box_Office_Crore : [175. 169. 222.  nan 445. 231. 188. 462. 379. 162. 455. 272. 309. 235.
 298. 320. 314. 192. 422. 296. 451. 154. 185. 410. 103. 157. 332. 239.
 177. 453.  64. 452. 412. 389. 333.  50. 456. 434. 125. 336. 190. 168.
  81. 230. 249. 251. 475.  85. 114. 209. 227. 258. 331. 430. 439. 343.
 255. 202. 290. 473. 189.  96. 437. 256. 197.  57. 174. 488. 253.  78.
  90. 276. 474. 167. 262. 472. 165. 113. 204. 325. 100. 471.  63. 265.
 245. 282. 350. 409. 224.  91. 304. 263. 104. 448. 124.  93. 381. 266.
 120. 128. 418. 307. 102. 312. 361. 199. 425. 313. 247. 358. 433. 363.
 415. 203. 171. 116. 413. 370.  80. 213. 173. 264. 305. 483. 341. 369.
  69. 322. 457. 419. 210. 294. 176. 252. 385. 429. 417. 500. 221. 218.
 288. 460. 338. 316. 431. 388. 164. 356. 492. 394. 352.]
Franchise_Name : ['Avatar Universe' 'DC' 'Star Wars' 'Marvel' 'Fast & Furious'
 'Mission Impossible' ' ?' 'Harry Potter']
Location : ['bangalore' 'mUMbAI' 'Chennai' 'Bangalore' 'mumbai' 'DELHI' 'BANGALORE'
 'Mumbai' 'kolkata' 'KolKATa' 'CHENNAI' 'MUMBAI' 'Delhi' 'mumbAi' 'DElHI'
 'baNGALoRE' 'mUmBAi' 'cHeNNaI' 'delhi' 'cHeNNai' 'BANgaLore' 'dElhI'
 'KOLKATA' 'dELhI' 'KOLKata' 'MUmBAi' 'KoLKaTa' 'mUMBAI' 'kolkaTa'
 'chennai' 'cheNNAi' 'Kolkata' 'delHI' 'DElHi' 'ChenNaI' 'kOLKatA'
 'BANgALoRe' 'CheNNai' 'CHennAI' 'BANGALOrE' 'KOlKAtA' 'KoLkaTa' 'kOLKATa'
 'chENnai' 'dELHI' 'koLkaTA' 'MUMbAi' 'bANGAlOre' 'chENNaI' 'MUmbai'
 'KOlKata' 'muMbaI' 'chEnnAI' 'DELhi' 'cHENnai' 'dELhi' 'kOlKatA' 'dELHi'
 'MUmBAI' 'MumBAI' 'BaNgAlORE' 'KoLkata' 'bANgAlorE' 'CHENnai' 'koLkATa']
Popularity : ['87%' '71%' '88%' '86%' '74%' '84%' '93%' '63%' '97%' '98%' '82%' '53%'
 '58%' '95%' '51%' '52%' '76%' '62%' '50%' '83%' '73%' '92%' '94%' '69%'
 '64%' '91%' '89%' '79%' '68%' '57%' '90%' '81%' '70%' '60%' '85%' '66%'
 '59%' '99%' '78%' '77%' '61%' '54%' '80%' '72%' '96%' '55%' '75%' '67%'
 '100%' '56%']

In [96]:
t=movi.Box_Office_Crore.fillna(movi.Box_Office_Crore.mean(),inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_9440\3686110222.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  t=movi.Box_Office_Crore.fillna(movi.Box_Office_Crore.mean(),inplace=True)

In [97]:
movi.isnull().sum()

Movie_Name           0
Genre                0
Rating              30
Box_Office_Crore     0
Franchise_Name       0
Location             0
Popularity           0
dtype: int64

In [98]:
movi

,Movie_Name,Genre,Rating,Box_Office_Crore,Franchise_Name,Location,Popularity
0,Dune,Action,1.0,175.000000,Avatar Universe,bangalore,87%
1,Matrix,Action,NaN,169.000000,DC,mUMbAI,71%
2,Joker,Drama,4.0,222.000000,Star Wars,Chennai,88%
3,Joker,Action,8.0,279.513514,DC,Bangalore,86%
4,Titanic,Action,1.0,445.000000,Marvel,mumbai,74%
...,...,...,...,...,...,...,...
195,Batman,Action,1.0,264.000000,Mission Impossible,DELHI,63%
196,Interstellar,Action,NaN,356.000000,Fast & Furious,mumbai,75%
197,Frozen,Drama,9.0,492.000000,?,CHENNAI,96%
198,Up,Comedy,10.0,394.000000,Fast & Furious,MUMBAI,76%
199,Joker,Comedy,1.0,352.000000,Harry Potter,koLkATa,69%

In [99]:
t=movi.Rating.fillna(movi.Rating.mean(),inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_9440\3304150214.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  t=movi.Rating.fillna(movi.Rating.mean(),inplace=True)

In [78]:
movi.isnull().sum()

Movie_Name          0
Genre               0
Rating              0
Box_Office_Crore    0
Location            0
Popularity          0
dtype: int64

In [100]:
movi['Franchise_Name']=movi['Franchise_Name'].replace(' ?',np.nan)

In [101]:
movi.describe(include='all')

,Movie_Name,Genre,Rating,Box_Office_Crore,Franchise_Name,Location,Popularity
count,200,200,200.000000,200.000000,159,200,200
unique,15,5,NaN,NaN,7,65,50
top,Joker,Sci-Fi,NaN,NaN,Star Wars,MUMBAI,83%
freq,24,45,NaN,NaN,27,13,8
mean,NaN,NaN,5.323529,279.513514,NaN,NaN,NaN
std,NaN,NaN,2.517482,118.431377,NaN,NaN,NaN
min,NaN,NaN,1.000000,50.000000,NaN,NaN,NaN
25%,NaN,NaN,3.000000,188.750000,NaN,NaN,NaN
50%,NaN,NaN,5.323529,279.513514,NaN,NaN,NaN
75%,NaN,NaN,7.000000,379.000000,NaN,NaN,NaN
max,NaN,NaN,10.000000,500.000000,NaN,NaN,NaN

In [103]:
t=movi.Franchise_Name.fillna('Star Wars')

In [104]:
movi

,Movie_Name,Genre,Rating,Box_Office_Crore,Franchise_Name,Location,Popularity
0,Dune,Action,1.000000,175.000000,Avatar Universe,bangalore,87%
1,Matrix,Action,5.323529,169.000000,DC,mUMbAI,71%
2,Joker,Drama,4.000000,222.000000,Star Wars,Chennai,88%
3,Joker,Action,8.000000,279.513514,DC,Bangalore,86%
4,Titanic,Action,1.000000,445.000000,Marvel,mumbai,74%
...,...,...,...,...,...,...,...
195,Batman,Action,1.000000,264.000000,Mission Impossible,DELHI,63%
196,Interstellar,Action,5.323529,356.000000,Fast & Furious,mumbai,75%
197,Frozen,Drama,9.000000,492.000000,NaN,CHENNAI,96%
198,Up,Comedy,10.000000,394.000000,Fast & Furious,MUMBAI,76%
199,Joker,Comedy,1.000000,352.000000,Harry Potter,koLkATa,69%

In [105]:
movi.describe(include='all')

,Movie_Name,Genre,Rating,Box_Office_Crore,Franchise_Name,Location,Popularity
count,200,200,200.000000,200.000000,159,200,200
unique,15,5,NaN,NaN,7,65,50
top,Joker,Sci-Fi,NaN,NaN,Star Wars,MUMBAI,83%
freq,24,45,NaN,NaN,27,13,8
mean,NaN,NaN,5.323529,279.513514,NaN,NaN,NaN
std,NaN,NaN,2.517482,118.431377,NaN,NaN,NaN
min,NaN,NaN,1.000000,50.000000,NaN,NaN,NaN
25%,NaN,NaN,3.000000,188.750000,NaN,NaN,NaN
50%,NaN,NaN,5.323529,279.513514,NaN,NaN,NaN
75%,NaN,NaN,7.000000,379.000000,NaN,NaN,NaN
max,NaN,NaN,10.000000,500.000000,NaN,NaN,NaN

In [109]:
movi['Popularity']=movi['Popularity'].str.replace('%','')
movi['Location']=movi['Location'].str.capitalize()
movi

,Movie_Name,Genre,Rating,Box_Office_Crore,Franchise_Name,Location,Popularity
0,Dune,Action,1.000000,175.000000,Avatar Universe,Bangalore,87
1,Matrix,Action,5.323529,169.000000,DC,Mumbai,71
2,Joker,Drama,4.000000,222.000000,Star Wars,Chennai,88
3,Joker,Action,8.000000,279.513514,DC,Bangalore,86
4,Titanic,Action,1.000000,445.000000,Marvel,Mumbai,74
...,...,...,...,...,...,...,...
195,Batman,Action,1.000000,264.000000,Mission Impossible,Delhi,63
196,Interstellar,Action,5.323529,356.000000,Fast & Furious,Mumbai,75
197,Frozen,Drama,9.000000,492.000000,NaN,Chennai,96
198,Up,Comedy,10.000000,394.000000,Fast & Furious,Mumbai,76
199,Joker,Comedy,1.000000,352.000000,Harry Potter,Kolkata,69